---
title: "Analysis of metabolite changes in SALK lines"
author: "Thomas Naake"
date: "04/07/2021"
fig_width: 15
fig_height: 10
output: 
    html_document:
    toc: true
toc_depth: 3
toc_float: TRUE
theme: united
number_sections: true
highlight: tango
self_contained: no
---
    
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = "pdf")
knitr::opts_knit$set(root.dir = "~/GitHub/GWAS_arabidopsis_seed/")
```

```{r load_packages, echo = FALSE}
suppressPackageStartupMessages(library("SummarizedExperiment"))
suppressPackageStartupMessages(library("MatrixQCvis"))
```

```{r functions, echo = FALSE}
## create function to get metabolites
get_metabolite <- function(pl, mz, rt) {
    rt <- rt * 60
    pl[pl[, "mz"] < mz + 0.01 & pl[, "mz"] > mz - 0.01 &
           pl[, "rt"] < rt + 60 & pl[, "rt"] > rt - 60, ] 
}

## create function to perform t-test
perform_ttest <- function(pl, line, n = 20, alternative = "two.sided") {
    
    ## add _ to line (to circumvent selection of the column of line that shows
    ## number of detected compounds)
    line <- paste(line, "_", sep = "")
    
    ## retrieve the columns that contain the intensitities
    col0 <- pl[, grep(colnames(pl), pattern = "Col_0_")]
    SALK_line <- pl[, grep(colnames(pl), pattern = line)]
    
    ## define the other lines (remove the line itself and the line on the same
    ## gene, if applicable)
    if (line == "SALK_008908_3_")
        other_lines <- c("SALK_011180_5", "SALK_020876_4", "SALK_021216_4", 
            "SALK_024438_5", "SALK_027837_5", "SALK_037430_4", "SALK_049338_4", 
            "SALK_072964_5", "SALK_081021_6", "SALK_201809C_2", 
            "SALK_203337C_2", "SALK_203919C_2", "SALK_204674C_3")
    
    if (line == "SALK_011180_5_")
        other_lines <- c("SALK_008908_3", "SALK_020876_4", "SALK_024438_5", 
            "SALK_027837_5", "SALK_037430_4", "SALK_049338_4", "SALK_072964_5", 
            "SALK_081021_6", "SALK_201809C_2", "SALK_203337C_2", 
            "SALK_203919C_2", "SALK_204674C_3")
    
    if (line == "SALK_020876_4_")   
        other_lines <- c("SALK_008908_3", "SALK_011180_5", "SALK_021216_4", 
            "SALK_024438_5", "SALK_037430_4", "SALK_049338_4", "SALK_072964_5", 
            "SALK_201809C_2", "SALK_203337C_2", "SALK_203919C_2",
            "SALK_204674C_3")
    
    if (line == "SALK_021216_4_")
        other_lines <- c("SALK_008908_3", "SALK_020876_4", "SALK_024438_5", 
            "SALK_027837_5", "SALK_037430_4", "SALK_049338_4", "SALK_072964_5", 
            "SALK_081021_6", "SALK_201809C_2", "SALK_203337C_2", 
            "SALK_203919C_2", "SALK_204674C_3")
    
    if (line == "SALK_024438_5_")
        other_lines <- c("SALK_008908_3", "SALK_011180_5", "SALK_020876_4",    
            "SALK_021216_4", "SALK_027837_5", "SALK_037430_4", "SALK_049338_4", 
            "SALK_072964_5", "SALK_081021_6", "SALK_201809C_2",   
            "SALK_203337C_2", "SALK_203919C_2", "SALK_204674C_3")
    
    if (line == "SALK_027837_5_")
        other_lines <- c("SALK_008908_3", "SALK_011180_5", "SALK_021216_4", 
            "SALK_024438_5", "SALK_037430_4", "SALK_049338_4", "SALK_072964_5", 
            "SALK_201809C_2", "SALK_203337C_2", "SALK_203919C_2", 
            "SALK_204674C_3")
    
    if (line == "SALK_037430_4_")
        other_lines <- c("SALK_008908_3", "SALK_011180_5", "SALK_020876_4",    
            "SALK_021216_4", "SALK_024438_5", "SALK_027837_5", "SALK_049338_4", 
            "SALK_072964_5", "SALK_081021_6", "SALK_201809C_2",   
            "SALK_203337C_2", "SALK_203919C_2", "SALK_204674C_3")
    
    if (line == "SALK_049338_4_")
        other_lines <- c("SALK_008908_3", "SALK_011180_5", "SALK_020876_4",    
            "SALK_021216_4", "SALK_024438_5", "SALK_027837_5", "SALK_072964_5", 
            "SALK_081021_6", "SALK_201809C_2", "SALK_203337C_2", 
            "SALK_203919C_2", "SALK_204674C_3")
    
    if (line == "SALK_072964_5_")  
        other_lines <- c("SALK_008908_3", "SALK_011180_5", "SALK_020876_4",    
            "SALK_021216_4", "SALK_024438_5", "SALK_027837_5", "SALK_037430_4", 
            "SALK_049338_4", "SALK_081021_6", "SALK_201809C_2",   
            "SALK_203337C_2", "SALK_203919C_2", "SALK_204674C_3")
    
    if (line == "SALK_081021_6_")
        other_lines <- c("SALK_008908_3", "SALK_011180_5", "SALK_021216_4", 
            "SALK_024438_5", "SALK_037430_4", "SALK_049338_4", "SALK_072964_5",
            "SALK_201809C_2", "SALK_203337C_2", "SALK_203919C_2", 
            "SALK_204674C_3")
    
    if (line == "SALK_201809C_2_")
        other_lines <- c("SALK_008908_3", "SALK_011180_5", "SALK_020876_4",    
            "SALK_021216_4", "SALK_024438_5", "SALK_027837_5", "SALK_037430_4", 
            "SALK_049338_4", "SALK_072964_5", "SALK_081021_6", "SALK_204674C_3")
    
    if (line == "SALK_203337C_2_")
        other_lines <- c("SALK_008908_3", "SALK_011180_5", "SALK_020876_4",    
            "SALK_021216_4", "SALK_024438_5", "SALK_027837_5", "SALK_037430_4", 
            "SALK_049338_4", "SALK_072964_5", "SALK_081021_6", "SALK_204674C_3")
    
    if (line == "SALK_203919C_2_")
        other_lines <- c("SALK_008908_3", "SALK_011180_5", "SALK_020876_4",    
            "SALK_021216_4", "SALK_024438_5", "SALK_027837_5", "SALK_037430_4", 
            "SALK_049338_4", "SALK_072964_5", "SALK_081021_6", "SALK_204674C_3")
    
    if (line == "SALK_204674C_3_")
        other_lines <- c("SALK_008908_3", "SALK_011180_5", "SALK_020876_4",    
            "SALK_021216_4", "SALK_024438_5", "SALK_027837_5", "SALK_037430_4", 
            "SALK_049338_4", "SALK_072964_5", "SALK_081021_6", "SALK_201809C_2",   
            "SALK_203337C_2", "SALK_203919C_2",)
    
    other_lines <- paste(other_lines, "_", sep = "")
    other_lines <- paste(other_lines, collapse = "|")
    other_SALK_lines <- pl[, grep(colnames(pl), pattern = other_lines)]
    
    ## perform the tests
    t_col0 <- t.test(x = col0, y = SALK_line)
    p_col0 <- p.adjust(t_col0$p.value, method = "BH", n = n)
    t_SALK <- t.test(x = other_SALK_lines, y = SALK_line)
    p_SALK <- p.adjust(t_SALK$p.value, method = "BH", n = n)
    
    ## return the elements
    list(ttest_Col0 = t_col0, adj_p_Col0 = p_col0,
         ttest_SALK_lines = t_SALK, adj_p_SALK_lines = p_SALK)
}
```


# Analysis

## Load the seed weights
```{r load_weights}
options(stringsAsFactors = FALSE)

## rep1
weights_rep1 <- openxlsx::read.xlsx("TDNA_rep1/mutant_lines_lc_weight.xlsx",
    sheet = 1)
weights_rep1$genotype <- gsub(weights_rep1$genotype, pattern = "[.]", 
    replacement = "_")
colnames(weights_rep1)[4] <- "weight"

## rep2
weights_rep2 <- openxlsx::read.xlsx("TDNA_rep2/mutant_lines_lc_weight_repl2.xlsx",
    sheet = 1)
weights_rep2$genotype <- gsub(weights_rep2$genotype, pattern = "[.]", 
    replacement = "_")
colnames(weights_rep2)[4] <- "weight"
```

## Negative mode

### Load and prepare the data 
```{r load_negative}
################################################################################
################################# negative mode ################################
################################################################################
## rep1
pl_rep1 <- read.table("TDNA_rep1/neg/TDNA_replicate1_neg_peaklist.txt", 
    header = TRUE, sep = "\t")
colnames(pl_rep1) <- gsub(colnames(pl_rep1), pattern = "_neg", replacement = "")
pl_rep1[pl_rep1 == 0] <- NA

## rep2
pl_rep2 <- read.table("TDNA_rep2/neg/TDNA_replicate2_neg_peaklist.txt", 
    header = TRUE, sep = "\t")
colnames(pl_rep2) <- gsub(colnames(pl_rep2), pattern = "_neg", replacement = "")
pl_rep2[pl_rep2 == 0] <- NA
```

Check data quality with `shinyQC`.
```{r shinyQC_prep_rep1}
## rep1
cols <- which(colnames(pl_rep1) == "C24_1"):which(colnames(pl_rep1) == "SALK_204674C_3_5")
a <- pl_rep1[, cols] |> as.matrix()
rD <- pl_rep1[, c("mz", "rt", "npeaks", "adduct", "pcgroup")]
cD <- data.frame(name = colnames(pl_rep1)[cols], 
    genotype = sort(weights_rep1$genotype),
    injection_number = weights_rep1$injection_vial[order(weights_rep1$genotype)])
cD$batch <- ifelse(cD$injection_number < 60, "1", "2")
se_rep1 <- SummarizedExperiment::SummarizedExperiment(assays = a, rowData = rD, colData = cD)
rownames(se_rep1) <- paste("feature", seq_len(nrow(se_rep1)), sep = "_")
```

```{r shinyQC_rep1, eval = FALSE}
MatrixQCvis::shinyQC(se_rep1)
```

```{r shinyQC_prep_rep2}
## rep2
cols <- which(colnames(pl_rep2) == "C24_1"):which(colnames(pl_rep2) == "SALK_204674C_3_5")
a <- pl_rep2[, cols] |> as.matrix()
rD <- pl_rep2[, c("mz", "rt", "npeaks", "adduct", "pcgroup")]
cD <- data.frame(name = colnames(pl_rep2)[cols])
cD <- data.frame(name = colnames(pl_rep2)[cols], 
    genotype = sort(weights_rep2$genotype),
    injection_number = weights_rep2$injection_vial[order(weights_rep2$genotype)])
cD$batch <- ifelse(cD$injection_number < 66, "1", "2")
se_rep2 <- SummarizedExperiment::SummarizedExperiment(assays = a, rowData = rD, colData = cD)
rownames(se_rep2) <- paste("feature", seq_len(nrow(se_rep2)), sep = "_")
```

```{r shinyQC_rep2, eval = FALSE}
MatrixQCvis::shinyQC(se_rep2)
```

Remove outliers
```{r outlier}
## rep1
outlier <- c("SALK_008908_3_14")
se_rep1 <- MatrixQCvis:::selectSampleSE(se_rep1, selection = outlier, 
    mode = "exclude")
weights_rep1 <- weights_rep1[!weights_rep1$genotype %in% outlier, ]

## rep2 
outlier <- c("SALK_201809C_2_3", "SALK_203919C_2_9", "SALK_081021_6_7", 
    "SALK_081021_6_5")
se_rep2 <- MatrixQCvis:::selectSampleSE(se_rep2, selection = outlier, 
    mode = "exclude")
weights_rep2 <- weights_rep2[!weights_rep2$genotype %in% outlier, ]
```

```{r transformation, warning = FALSE, message = FALSE}
## divide by weight
assay(se_rep1)[, weights_rep1$genotype] <- sweep(assay(se_rep1)[, weights_rep1$genotype], 
    MARGIN = 2, STATS = weights_rep1$weight, FUN = "/")
assay(se_rep2)[, weights_rep2$genotype] <- sweep(assay(se_rep2)[, weights_rep2$genotype], 
    MARGIN = 2, STATS = weights_rep2$weight, FUN = "/")

## batch correction
## rep1 
pl_rep1 <- MatrixQCvis::batchCorrectionAssay(se_rep1, 
    method = "removeBatchEffect (limma)", batchColumn = "batch")
pl_rep1 <- cbind(rowData(se_rep1), pl_rep1) |> as.data.frame()

## rep2
pl_rep2 <- MatrixQCvis::batchCorrectionAssay(se_rep2, 
    method = "removeBatchEffect (limma)", batchColumn = "batch")
pl_rep2 <- cbind(rowData(se_rep2), pl_rep2) |> as.data.frame()

## take log2 values
pl_rep1[, weights_rep1$genotype] <- log2(pl_rep1[, weights_rep1$genotype] + 1)
pl_rep2[, weights_rep2$genotype] <- log2(pl_rep2[, weights_rep2$genotype] + 1)

## impute the NA values
pl_rep1[, weights_rep1$genotype] <- pl_rep1[, weights_rep1$genotype] |> 
    as.matrix() |> 
    imputeAssay(method = "MinDet")
pl_rep2[, weights_rep2$genotype] <- pl_rep2[, weights_rep2$genotype] |>
    as.matrix() |>
    imputeAssay(method = "MinDet")
```

### Perform t-tests

#### SALK_037430
```{r ttests}
n <- 2
## Cluster_30089/Cluster_061967
pl_sel <- get_metabolite(pl = pl_rep1, mz = 498.1259, rt = 8.23)
perform_ttest(pl = pl_sel, line = "SALK_037430_4", n = n) ## 498.1257/8.23:
pl_sel <- get_metabolite(pl = pl_rep2, mz = 498.1259, rt = 8.23)
perform_ttest(pl = pl_sel, line = "SALK_037430_4", n = 2, "greater") ## 498.1259/8.16

## Cluster_32016/Cluster_067344
pl_sel <- get_metabolite(pl = pl_rep1, mz = 537.1982, rt = 5.02)
perform_ttest(pl = pl_sel[1, ], line = "SALK_037430_4", n = n) ## 537.1982/5.02
perform_ttest(pl = pl_sel[2, ], line = "SALK_037430_4", n = n) ## 537.1977/5.77
pl_sel <- get_metabolite(pl = pl_rep2, mz = 537.1982, rt = 5.02)
perform_ttest(pl = pl_sel[1, ], line = "SALK_037430_4", n = n, "greater") ## 537.1980/4.98
perform_ttest(pl = pl_sel[2, ], line = "SALK_037430_4", n = n, "greater") ## 537.1983/5.72

## Cluster_42555/Cluster_090947
pl_sel <- get_metabolite(pl = pl_rep1, mz = 728.2757, rt = 4.88) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_037430_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 728.2757, rt = 4.88) ## 728.2783/4.78
#perform_ttest(pl = pl_sel, line = "SALK_037430_4", n = n) ## 

## Cluster_42557/Cluster_090947
pl_sel <- get_metabolite(pl = pl_rep1, mz = 728.2774, rt = 5.04) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_037430_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 728.2774, rt = 5.04) 
#perform_ttest(pl = pl_sel, line = "SALK_037430_4", n = n) ## 728.2783/4.78

## Cluster_26137/Cluster_050014
pl_sel <- get_metabolite(pl = pl_rep1, mz = 413.1093, rt = 3.57) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_037430_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 413.1093, rt = 3.75) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_037430_4", n = n)
```

#### SALK_072964
```{r}
n <- 7
## Cluster_26908/Cluster_052602
pl_sel <- get_metabolite(pl = pl_rep1, mz = 431.1191, rt = 3.57)
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n) ## 431.1197/3.78
pl_sel <- get_metabolite(pl = pl_rep2, mz = 431.1191, rt = 3.57) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n)

## Cluster_26909/Cluster_052602
pl_sel <- get_metabolite(pl = pl_rep1, mz = 431.1194, rt = 3.69)
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n) ## 431.1197/3.78
pl_sel <- get_metabolite(pl = pl_rep2, mz = 431.1194, rt = 3.69) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n)

## Cluster_28240/Cluster_056944
pl_sel <- get_metabolite(pl = pl_rep1, mz = 461.1303, rt = 3.85)
perform_ttest(pl = pl_sel[1, ], line = "SALK_072964_5", n = n) ## 461.1338/3.47
perform_ttest(pl = pl_sel[2, ], line = "SALK_072964_5", n = n) ## 461.1305/3.92
pl_sel <- get_metabolite(pl = pl_rep2, mz = 461.1303, rt = 3.85)
perform_ttest(pl = pl_sel[1, ], line = "SALK_072964_5", n = n, "greater") ## 461.1302/4.34
perform_ttest(pl = pl_sel[2, ], line = "SALK_072964_5", n = n, "greater") ## 461.1338/3.44

## Cluster_29139/Cluster_059193
pl_sel <- get_metabolite(pl = pl_rep1, mz = 477.1249, rt = 3.69)
perform_ttest(pl = pl_sel[1, ], line = "SALK_072964_5", n = n) ## 477.1186/4.65
#perform_ttest(pl = pl_sel[2, ], line = "SALK_072964_5", n = n) ## 477.1251/2.95, too many NAs
pl_sel <- get_metabolite(pl = pl_rep2, mz = 477.1249, rt = 3.69)
perform_ttest(pl = pl_sel[1, ], line = "SALK_072964_5", n = n, "greater") ## 477.1183/4.51
perform_ttest(pl = pl_sel[2, ], line = "SALK_072964_5", n = n, "greater") ## 477.1256/2.91

## Cluster_30139/Cluster_062059
pl_sel <- get_metabolite(pl = pl_rep1, mz = 499.1073, rt = 3.69) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n) 
pl_sel <- get_metabolite(pl = pl_rep2, mz = 499.1073, rt = 3.69)
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n) ## 499.1044/2.99

## Cluster_31590/Cluster_066227
pl_sel <- get_metabolite(pl = pl_rep1, mz = 529.1178, rt = 3.85)
##perform_ttest(pl = pl_sel[1, ], line = "SALK_072964_5", n = n) ## 529.1177/3.92, too many NAs
perform_ttest(pl = pl_sel[2, ], line = "SALK_072964_5", n = n) ## 529.1178/3.69
pl_sel <- get_metabolite(pl = pl_rep2, mz = 529.1178, rt = 3.85)
perform_ttest(pl = pl_sel[1, ], line = "SALK_072964_5", n = n, "less") ## 529.1173/4.42
perform_ttest(pl = pl_sel[2, ], line = "SALK_072964_5", n = n, "less") ## 529.1149/3.33

## Cluster_31874/Cluster_067055
pl_sel <- get_metabolite(pl = pl_rep1, mz = 535.1463, rt = 7.12)
perform_ttest(pl = pl_sel[1, ], line = "SALK_072964_5", n = n) ## 535.1462/7.82
perform_ttest(pl = pl_sel[2, ], line = "SALK_072964_5", n = n) ## 535.1461/8.03
pl_sel <- get_metabolite(pl = pl_rep2, mz = 535.1463, rt = 7.12)
perform_ttest(pl = pl_sel[2, ], line = "SALK_072964_5", n = n, "greater") ## 535.1494/7.47
perform_ttest(pl = pl_sel[1, ], line = "SALK_072964_5", n = n, "less") ## 535.1465/8.10


## Cluster_31923/Cluster_067181
pl_sel <- get_metabolite(pl = pl_rep1, mz = 536.1410, rt = 5.01) 
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n) ## 536.1410/5.04
pl_sel <- get_metabolite(pl = pl_rep2, mz = 536.1410, rt = 5.01) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n)

## Cluster_32713/Cluster_069229
pl_sel <- get_metabolite(pl = pl_rep1, mz = 551.1416, rt = 5.90)
perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n) ## 551.1413/5.94
pl_sel <- get_metabolite(pl = pl_rep2, mz = 551.1416, rt = 5.90)
perform_ttest(pl = pl_sel[1, ], line = "SALK_072964_5", n = n, "greater") ## 551.1417/6.26
perform_ttest(pl = pl_sel[2, ], line = "SALK_072964_5", n = n, "greater") ## 551.1425/5.88

## Cluster_33259/Cluster_070830
pl_sel <- get_metabolite(pl = pl_rep1, mz = 561.0771, rt = 3.69) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 561.0771, rt = 3.69) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n)

## Cluster_35713/Cluster_076522
pl_sel <- get_metabolite(pl = pl_rep1, mz = 603.2200, rt = 6.21)
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n) ## 603.2196/6.22
pl_sel <- get_metabolite(pl = pl_rep2, mz = 603.2200, rt = 6.21) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n)

## Cluster_36010/Cluster_077152
pl_sel <- get_metabolite(pl = pl_rep1, mz = 608.2201, rt = 2.99)
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n) ## 608.2195/3.29
pl_sel <- get_metabolite(pl = pl_rep2, mz = 608.2201, rt = 2.99) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n)

## Cluster_39441/Cluster_084545
pl_sel <- get_metabolite(pl = pl_rep1, mz = 667.1883, rt = 6.86)
perform_ttest(pl = pl_sel[1, ], line = "SALK_072964_5", n = n) ## 667.1884/7.24
perform_ttest(pl = pl_sel[2, ], line = "SALK_072964_5", n = n) ## 667.1889/7.02
pl_sel <- get_metabolite(pl = pl_rep2, mz = 667.1883, rt = 6.86)
perform_ttest(pl = pl_sel[2, ], line = "SALK_072964_5", n = n, "greater") ## 667.1893/7.18
perform_ttest(pl = pl_sel[1, ], line = "SALK_072964_5", n = n, "greater") ## 667.1894/6.97

## Cluster_42608/Cluster_091037
pl_sel <- get_metabolite(pl = pl_rep1, mz = 729.1679, rt = 7.78)
perform_ttest(pl = pl_sel[1, ], line = "SALK_072964_5", n = n) ## 729.1683/7.80
perform_ttest(pl = pl_sel[2, ], line = "SALK_072964_5", n = n) ## 729.1680/7.50
pl_sel <- get_metabolite(pl = pl_rep2, mz = 729.1679, rt = 7.78)
perform_ttest(pl = pl_sel[2, ], line = "SALK_072964_5", n = n, "less") ## 729.1682/7.74
perform_ttest(pl = pl_sel[1, ], line = "SALK_072964_5", n = n, "less") ## 729.1687/7.46


## Cluster_44863/Cluster_095588
pl_sel <- get_metabolite(pl = pl_rep1, mz = 777.2247, rt = 6.38)
#perform_ttest(pl = pl_sel[1, ], line = "SALK_072964_5", n = n) ## 777.2261/6.42
#perform_ttest(pl = pl_sel[2, ], line = "SALK_072964_5", n = n) ## 777.2251/7.23
pl_sel <- get_metabolite(pl = pl_rep2, mz = 777.2247, rt = 6.38) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n)

## Cluster_45928/Cluster_097741
pl_sel <- get_metabolite(pl = pl_rep1, mz = 803.2406, rt = 7.12) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 803.2406, rt = 7.12) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n)

## Cluster_47541/Cluster_100876
pl_sel <- get_metabolite(pl = pl_rep1, mz = 845.2356, rt = 4.98)
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n) ## 845.2365/5.01
pl_sel <- get_metabolite(pl = pl_rep2, mz = 845.2356, rt = 4.98) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_072964_5", n = n)
```

#### SALK_024438

```{r salk_024438}
n <- 3
## Cluster_26220/Cluster_050308
pl_sel <- get_metabolite(pl = pl_rep1, mz = 415.1264, rt = 8.16)
perform_ttest(pl = pl_sel, line = "SALK_024438_5", n = n) ## 415.1263/8.21
pl_sel <- get_metabolite(pl = pl_rep2, mz = 415.1264, rt = 8.16)
perform_ttest(pl = pl_sel, line = "SALK_024438_5", n = n, "greater") ## 415.1266/8.17

## Cluster_29119/Cluster_059172
pl_sel <- get_metabolite(pl = pl_rep1, mz = 477.0638, rt = 6.33)
perform_ttest(pl = pl_sel[1, ], line = "SALK_024438_5", n = n) ## 477.0643/5.47
perform_ttest(pl = pl_sel[2, ], line = "SALK_024438_5", n = n) ## 477.0645/6.38
perform_ttest(pl = pl_sel[3, ], line = "SALK_024438_5", n = n) ## 477.0676/7.03
perform_ttest(pl = pl_sel[4, ], line = "SALK_024438_5", n = n) ## 477.0673/5.86
pl_sel <- get_metabolite(pl = pl_rep2, mz = 477.0638, rt = 6.33)
perform_ttest(pl = pl_sel[2, ], line = "SALK_024438_5", n = n, "less") ## 477.0646/5.55
perform_ttest(pl = pl_sel[1, ], line = "SALK_024438_5", n = n, "less") ## 477.0650/6.48
perform_ttest(pl = pl_sel[4, ], line = "SALK_024438_5", n = n, "greater") ## 477.0709/7.00
perform_ttest(pl = pl_sel[3, ], line = "SALK_024438_5", n = n, "less") ## 477.0678/5.89


## Cluster_35940/Cluster_076981
pl_sel <- get_metabolite(pl = pl_rep1, mz = 607.0222, rt = 6.33) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_024438_5", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 607.0222, rt = 6.33) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_024438_5", n = n)

## Cluster_36285/Cluster_077756
pl_sel <- get_metabolite(pl = pl_rep1, mz = 613.0401, rt = 6.33)
perform_ttest(pl = pl_sel[1, ], line = "SALK_024438_5", n = n) ## 613.0398/6.39
#perform_ttest(pl = pl_sel[2, ], line = "SALK_024438_5", n = n) ## 613.0400/5.39
pl_sel <- get_metabolite(pl = pl_rep2, mz = 613.0401, rt = 6.33)
perform_ttest(pl = pl_sel, line = "SALK_024438_5", n = n, "greater") ## 613.0476/7.00

## Cluster_36917/Cluster_079278
pl_sel <- get_metabolite(pl = pl_rep1, mz = 625.1013, rt = 4.17) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_024438_5", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 625.1013, rt = 4.17) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_024438_5", n = n)
```

#### SALK_011180/SALK_021216/SALK_049338

```{r salk_011180_021216_049338}
n <- 22
## Cluster_27573/Cluster_054996
pl_sel <- get_metabolite(pl = pl_rep1, mz = 477.0939, rt = 7.42)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n) ## 477.0872/8.19
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 477.0939, rt = 7.42)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n, "less") ## 477.0883/7.87
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n, "less")
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n, "greater")

## Cluster_28337/Cluster_057215
pl_sel <- get_metabolite(pl = pl_rep1, mz = 463.0882, rt = 6.94)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n) ## 463.0885/7.08
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n)
perform_ttest(pl = pl_sel[2, ], line = "SALK_011180_5", n = n) ## 463.0885/6.12
perform_ttest(pl = pl_sel[2, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[2, ], line = "SALK_049338_4", n = n)
# perform_ttest(pl = pl_sel[3, ], line = "SALK_011180_5", n = n) ## 463.0965/7.54
# perform_ttest(pl = pl_sel[3, ], line = "SALK_021216_4", n = n)
# perform_ttest(pl = pl_sel[3, ], line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 463.0882, rt = 6.94)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n, "greater") ## 463.0890/7.01
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n, "greater")
perform_ttest(pl = pl_sel[2, ], line = "SALK_011180_5", n = n, "less") ## 463.0889/6.24
perform_ttest(pl = pl_sel[2, ], line = "SALK_021216_4", n = n, "less")
perform_ttest(pl = pl_sel[2, ], line = "SALK_049338_4", n = n, "less")
# perform_ttest(pl = pl_sel[3, ], line = "SALK_011180_5", n = n) ## 463.0968/7.68
# perform_ttest(pl = pl_sel[3, ], line = "SALK_021216_4", n = n)
# perform_ttest(pl = pl_sel[3, ], line = "SALK_049338_4", n = n)

## Cluster_31680/Cluster_066469
pl_sel <- get_metabolite(pl = pl_rep1, mz = 531.0760, rt = 6.95)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n) ## 531.0761/7.07
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n)
# perform_ttest(pl = pl_sel[2, ], line = "SALK_011180_5", n = n) ## 531.0838/7.55
# perform_ttest(pl = pl_sel[2, ], line = "SALK_021216_4", n = n)
# perform_ttest(pl = pl_sel[2, ], line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 531.0760, rt = 6.95)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n, "greater") ## 531.0764/7.02
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n, "greater")
# perform_ttest(pl = pl_sel[2, ], line = "SALK_011180_5", n = n, "less") ## 531.0842/7.70
# perform_ttest(pl = pl_sel[2, ], line = "SALK_021216_4", n = n, "less")
# perform_ttest(pl = pl_sel[2, ], line = "SALK_049338_4", n = n, "less")

## Cluster_35169/Cluster_075199
pl_sel <- get_metabolite(pl = pl_rep1, mz = 593.1515, rt = 6.43)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n) ## 593.1516/6.73
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n)
perform_ttest(pl = pl_sel[2, ], line = "SALK_011180_5", n = n) ## 593.1518/6.00
perform_ttest(pl = pl_sel[2, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[2, ], line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 593.1515, rt = 6.43)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n, "greater") ## 593.1519/6.68
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n, "greater")
perform_ttest(pl = pl_sel[2, ], line = "SALK_011180_5", n = n, "greater") ## 593.1519/5.95
perform_ttest(pl = pl_sel[2, ], line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel[2, ], line = "SALK_049338_4", n = n, "greater")


## Cluster_36050/Cluster_077251
pl_sel <- get_metabolite(pl = pl_rep1, mz = 609.1464, rt = 6.05)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n) ## 609.1466/6.20
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n)
perform_ttest(pl = pl_sel[2, ], line = "SALK_011180_5", n = n) ## 609.1462/5.56
perform_ttest(pl = pl_sel[2, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[2, ], line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 609.1464, rt = 6.05)
perform_ttest(pl = pl_sel[2, ], line = "SALK_011180_5", n = n, "greater") ## 609.1469/6.15
perform_ttest(pl = pl_sel[2, ], line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel[2, ], line = "SALK_049338_4", n = n, "less")
perform_ttest(pl = pl_sel[3, ], line = "SALK_011180_5", n = n, "less") ## 609.1466/5.52
perform_ttest(pl = pl_sel[3, ], line = "SALK_021216_4", n = n, "less")
perform_ttest(pl = pl_sel[3, ], line = "SALK_049338_4", n = n, "less")

## Cluster_36813/Cluster_079019
pl_sel <- get_metabolite(pl = pl_rep1, mz = 623.1617, rt = 6.65)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n) ## 623.1625/6.79
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n)
perform_ttest(pl = pl_sel[2, ], line = "SALK_011180_5", n = n) ## 623.1621/7.24
perform_ttest(pl = pl_sel[2, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[2, ], line = "SALK_049338_4", n = n)
perform_ttest(pl = pl_sel[3, ], line = "SALK_011180_5", n = n) ## 623.1619/6.15
perform_ttest(pl = pl_sel[3, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[3, ], line = "SALK_049338_4", n = n)
perform_ttest(pl = pl_sel[4, ], line = "SALK_011180_5", n = n) ## 623.1598/5.66
perform_ttest(pl = pl_sel[4, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[4, ], line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 623.1617, rt = 6.65)
perform_ttest(pl = pl_sel[2, ], line = "SALK_011180_5", n = n, "greater") ## 623.1629/6.74
perform_ttest(pl = pl_sel[2, ], line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel[2, ], line = "SALK_049338_4", n = n, "greater")
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n, "greater") ## 623.1624/7.18
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n, "greater")
perform_ttest(pl = pl_sel[3, ], line = "SALK_011180_5", n = n, "greater") ## 623.1621/6.10
perform_ttest(pl = pl_sel[3, ], line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel[3, ], line = "SALK_049338_4", n = n, "less")
perform_ttest(pl = pl_sel[4, ], line = "SALK_011180_5", n = n, "less") ## 623.1603/5.77
perform_ttest(pl = pl_sel[4, ], line = "SALK_021216_4", n = n, "less")
perform_ttest(pl = pl_sel[4, ], line = "SALK_049338_4", n = n, "less")

## Cluster_36921/Cluster_079272
pl_sel <- get_metabolite(pl = pl_rep1, mz = 625.1408, rt = 6.27)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n) ## 625.1416/6.12
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 625.1408, rt = 6.27)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n, "greater") ## 625.1417/6.07
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n, "greater")
perform_ttest(pl = pl_sel[2, ], line = "SALK_011180_5", n = n, "greater") ## 625.1418/6.29
perform_ttest(pl = pl_sel[2, ], line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel[2, ], line = "SALK_049338_4", n = n, "greater")
perform_ttest(pl = pl_sel[4, ], line = "SALK_011180_5", n = n, "greater") ## 625.1374/5.87
perform_ttest(pl = pl_sel[4, ], line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel[4, ], line = "SALK_049338_4", n = n, "greater")

## Cluster_38140/Cluster_081769
pl_sel <- get_metabolite(pl = pl_rep1, mz = 645.1232, rt = 6.05)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n) ## 645.1229/6.20
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n)
perform_ttest(pl = pl_sel[2, ], line = "SALK_011180_5", n = n) ## 645.1236/5.36
perform_ttest(pl = pl_sel[2, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[2, ], line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 645.1232, rt = 6.05)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n, "greater") ## 645.1233/6.15
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n, "greater")
perform_ttest(pl = pl_sel[4, ], line = "SALK_011180_5", n = n, "less") ## 645.1235/5.53
perform_ttest(pl = pl_sel[4, ], line = "SALK_021216_4", n = n, "less")
perform_ttest(pl = pl_sel[4, ], line = "SALK_049338_4", n = n, "less")

## Cluster_38744/Cluster_083055
pl_sel <- get_metabolite(pl = pl_rep1, mz = 655.1520, rt = 6.05)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n) ## 655.1519/6.20
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n)
perform_ttest(pl = pl_sel[3, ], line = "SALK_011180_5", n = n) ## 655.1531/6.79
perform_ttest(pl = pl_sel[3, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[3, ], line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 655.1520, rt = 6.05)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n, "greater") ## 655.1521/6.15
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n, "greater")
perform_ttest(pl = pl_sel[3, ], line = "SALK_011180_5", n = n, "less") ## 655.1539/6.73
perform_ttest(pl = pl_sel[3, ], line = "SALK_021216_4", n = n, "less")
perform_ttest(pl = pl_sel[3, ], line = "SALK_049338_4", n = n, "less")

## Cluster_39122/Cluster_083810
pl_sel <- get_metabolite(pl = pl_rep1, mz = 661.1390, rt = 6.43)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n) ## 661.1390/6.73
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 661.1390, rt = 6.43)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n, "greater") ## 661.1393/6.68
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n, "greater")


## Cluster_39933/Cluster_085577
pl_sel <- get_metabolite(pl = pl_rep1, mz = 677.1342, rt = 6.05)
perform_ttest(pl = pl_sel[2, ], line = "SALK_011180_5", n = n,) ## 677.1340/6.19
perform_ttest(pl = pl_sel[2, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[2, ], line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 677.1342, rt = 6.05)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n, "greater") ## 677.1343/6.14
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n, "greater")


## Cluster_41440/Cluster_088739
pl_sel <- get_metabolite(pl = pl_rep1, mz = 707.1211, rt = 6.05)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n) ## 707.1236/6.89
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n)
perform_ttest(pl = pl_sel[2, ], line = "SALK_011180_5", n = n) ## 707.1172/6.20
perform_ttest(pl = pl_sel[2, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[2, ], line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 707.1211, rt = 6.05)
perform_ttest(pl = pl_sel[2, ], line = "SALK_011180_5", n = n, "less") ## 707.1238/6.83
perform_ttest(pl = pl_sel[2, ], line = "SALK_021216_4", n = n, "less")
perform_ttest(pl = pl_sel[2, ], line = "SALK_049338_4", n = n, "less")
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n, "greater") ## 707.1188/6.14
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n, "greater")


## Cluster_41494/Cluster_088839
pl_sel <- get_metabolite(pl = pl_rep1, mz = 708.0628, rt = 6.05)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n) ## 708.0637/6.20
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 708.0628, rt = 6.05)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n, "greater") ## 708.0635/6.14
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n, "greater")

## Cluster_42266/Cluster_090361
pl_sel <- get_metabolite(pl = pl_rep1, mz = 723.1390, rt = 6.05)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n) ## 723.1398/6.19
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 723.1390, rt = 6.05)
perform_ttest(pl = pl_sel[1, ], line = "SALK_011180_5", n = n, "greater") ## 723.1403/6.15
perform_ttest(pl = pl_sel[1, ], line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel[1, ], line = "SALK_049338_4", n = n, "greater")

## Cluster_43042/Cluster_091992
pl_sel <- get_metabolite(pl = pl_rep1, mz = 739.1040, rt = 6.05)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n) ## 739.1060/6.19
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 739.1040, rt = 6.05)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n, "greater") ## 739.1058/6.14
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n, "greater")

## Cluster_43398/Cluster_092629
pl_sel <- get_metabolite(pl = pl_rep1, mz = 745.1224, rt = 6.05)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n) ## 745.1216/6.20
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 745.1224, rt = 6.05)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n, "greater") ## 745.1221/6.14
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n, "greater")

## Cluster_44151/Cluster_010308
pl_sel <- get_metabolite(pl = pl_rep1, mz = 761.0875, rt = 6.05)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n) ## 761.0928/6.19
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 761.0875, rt = 6.05) 
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n, "greater") ## 761.0948/6.14
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n, "greater")

## Cluster_46078/Cluster_098040
pl_sel <- get_metabolite(pl = pl_rep1, mz = 807.0911, rt = 6.05)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n) ## 807.0925/6.19
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 807.0911, rt = 6.05)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n, "greater") ## 807.0944/6.14
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n, "greater")

## Cluster_46322/Cluster_098526
pl_sel <- get_metabolite(pl = pl_rep1, mz = 813.1080, rt = 6.05)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n) ## 813.1088/6.19
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 813.1080, rt = 6.05)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n, "greater") ## 813.1099/6.14
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n, "greater")

## Cluster_46959/Cluster_011972
pl_sel <- get_metabolite(pl = pl_rep1, mz = 829.0748, rt = 6.05)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n) ## 829.0803/6.19
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 829.0748, rt = 6.05)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n, "greater") ## 829.0820/6.14
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n, "greater")

## Cluster_48505/Cluster_102833
pl_sel <- get_metabolite(pl = pl_rep1, mz = 875.0775, rt = 6.05) ## n.f.
#perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n)
#perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n)
#perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 875.0775, rt = 6.05)
#perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n) ## 875.0791/6.13
#perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n)
#perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n)

## Cluster_51012/Cluster_107244
pl_sel <- get_metabolite(pl = pl_rep1, mz = 958.0279, rt = 6.05)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n) ## 958.0318/6.19
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 958.0279, rt = 6.05)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n, "less") ## 958.0318/6.12
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n, "less")
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n, "greater")

## Cluster_56819/Cluster_114131
pl_sel <- get_metabolite(pl = pl_rep1, mz = 1219.2990, rt = 6.05)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n) ## 1219.3000/6.20
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n)
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n)
pl_sel <- get_metabolite(pl = pl_rep2, mz = 1219.2990, rt = 6.05)
perform_ttest(pl = pl_sel, line = "SALK_011180_5", n = n, "greater") ## 1219.3000/6.15
perform_ttest(pl = pl_sel, line = "SALK_021216_4", n = n, "greater")
perform_ttest(pl = pl_sel, line = "SALK_049338_4", n = n, "greater")
```

